### ISSUE TITLE
EduTrac Installation (requirements.pip)

### ISSUE THREAD

**Issue by ghost** [unicefuganda/edtrac#3]
Hi,

I'm trying to install EduTrac, I have reached the step where I need to pip install the requirements.pip but found the following error, any ideas what I should do to fix this?

`(edtrac) [root@ip-192-168-0-49 edtrac]# pip install -r requirements.pip
Collecting Django==1.4.10 (from -r requirements.pip (line 1))
  Downloading Django-1.4.10.tar.gz (7.7MB)
    100% |████████████████████████████████| 7.8MB 157kB/s
Collecting PyYAML==3.10 (from -r requirements.pip (line 2))
  Downloading PyYAML-3.10.tar.gz (241kB)
    100% |████████████████████████████████| 245kB 4.4MB/s
Collecting South==0.8.4 (from -r requirements.pip (line 3))
  Downloading South-0.8.4-py2.py3-none-any.whl (135kB)
    100% |████████████████████████████████| 143kB 7.6MB/s
Collecting amqp==1.3.3 (from -r requirements.pip (line 4))
  Downloading amqp-1.3.3.tar.gz (75kB)
    100% |████████████████████████████████| 81kB 9.8MB/s
Collecting anyjson==0.3.3 (from -r requirements.pip (line 5))
  Downloading anyjson-0.3.3.tar.gz
Collecting argparse==1.2.1 (from -r requirements.pip (line 6))
  Downloading argparse-1.2.1.tar.gz (69kB)
    100% |████████████████████████████████| 71kB 9.0MB/s
Collecting billiard==3.3.0.11 (from -r requirements.pip (line 7))
  Downloading billiard-3.3.0.11.tar.gz (148kB)
    100% |████████████████████████████████| 153kB 7.0MB/s
Collecting celery==3.1.6 (from -r requirements.pip (line 8))
  Downloading celery-3.1.6.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 969kB/s
Collecting coverage==3.7 (from -r requirements.pip (line 9))
  Downloading coverage-3.7.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 3.9MB/s
Collecting dateutils==0.6.6 (from -r requirements.pip (line 10))
  Downloading dateutils-0.6.6.tar.gz
Collecting django-celery==3.1.1 (from -r requirements.pip (line 11))
  Downloading django-celery-3.1.1.tar.gz (75kB)
    100% |████████████████████████████████| 81kB 9.3MB/s
Collecting django-debug-toolbar==0.9.4 (from -r requirements.pip (line 12))
  Downloading django-debug-toolbar-0.9.4.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 6.9MB/s
Collecting django-digest==1.13 (from -r requirements.pip (line 13))
  Downloading django-digest-1.13.tar.gz
Collecting django-extensions==1.2.5 (from -r requirements.pip (line 14))
  Downloading django-extensions-1.2.5.tar.gz (285kB)
    100% |████████████████████████████████| 286kB 3.9MB/s
Collecting django-mptt==0.4.2 (from -r requirements.pip (line 15))
  Downloading django-mptt-0.4.2.zip (71kB)
    100% |████████████████████████████████| 71kB 8.8MB/s
Collecting django-nose==1.2 (from -r requirements.pip (line 16))
  Downloading django-nose-1.2.tar.gz
Collecting django-picklefield==0.3.1 (from -r requirements.pip (line 17))
  Downloading django-picklefield-0.3.1.tar.gz
Collecting django-tablib==2.5 (from -r requirements.pip (line 18))
  Downloading django-tablib-2.5.tar.gz
Collecting django-tastypie==0.10.0 (from -r requirements.pip (line 19))
  Downloading django-tastypie-0.10.0.tar.gz (721kB)
    100% |████████████████████████████████| 727kB 1.5MB/s
Collecting django-uni-form==0.9.0 (from -r requirements.pip (line 20))
  Downloading django-uni-form-0.9.0.tar.gz (62kB)
    100% |████████████████████████████████| 71kB 9.5MB/s
Collecting djappsettings==0.1.0 (from -r requirements.pip (line 21))
  Downloading djappsettings-0.1.0.tar.gz
Collecting djtables==0.1.2 (from -r requirements.pip (line 22))
  Downloading djtables-0.1.2.tar.gz
Collecting httplib2==0.8 (from -r requirements.pip (line 23))
  Downloading httplib2-0.8.zip (116kB)
    100% |████████████████████████████████| 122kB 8.1MB/s
Collecting kombu==3.0.7 (from -r requirements.pip (line 24))
  Downloading kombu-3.0.7.tar.gz (330kB)
    100% |████████████████████████████████| 337kB 3.6MB/s
Collecting mock==1.0.1 (from -r requirements.pip (line 25))
  Downloading mock-1.0.1.zip (861kB)
    100% |████████████████████████████████| 870kB 1.4MB/s
Collecting nltk==2.0.4 (from -r requirements.pip (line 26))
  Downloading nltk-2.0.4.zip (1.1MB)
    100% |████████████████████████████████| 1.1MB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpFVzJR1
    Now working in /tmp/tmpFVzJR1/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-XxjATR/nltk
    /tmp/pip-build-XxjATR/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-XxjATR/nltk/setup.py", line 32, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-XxjATR/nltk/
(edtrac) `

Thanks!

**Comment by supportticanalyse** [comment]
Hi! i have the same problem could you help me? could you tell me how did you fix this issue?
